### ISSUE TITLE
ArgumentOutOfRangeException in EnforceFileVersionIsSameAsPackageVersionAnalyzer

### ISSUE THREAD

**Issue by jafaber** [philips-software/roslyn-analyzers#667]
```
warning AD0001: Analyzer 'Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.EnforceFileVersionIsSameAsPackageVersionAnalyzer'
 threw an exception of type 'System.ArgumentOutOfRangeException'
 with message 'Version's parameters must be greater than or equal to zero.

System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero. (Parameter 'build')
   at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
   at Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.EnforceFileVersionIsSameAsPackageVersionAnalyzer.SetRevisionToZeroIfMissing(Version version)
   at Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.EnforceFileVersionIsSameAsPackageVersionAnalyzer.Analyze(CompilationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationActions>b__41_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
```

**Comment by bcollamore** [comment]
Hi @jafaber thank you for submitting an issue. We will investigate. In the meantime, could you provide details? For example, what is the build (major.minor.build.revision) for your project?

**Comment by jafaber** [comment]
I had only Version 3.3 and no other version related properties.

```
  <PropertyGroup>
    <Version>3.3</Version>
  </PropertyGroup>

```

I have since changed that to `3.3.0.0`, to successfully workaround the exception:

```
  <PropertyGroup>
    <Version>3.3.0.0</Version>
  </PropertyGroup>

```

Thanks.
