### ISSUE TITLE
InvalidOperationException and IndexOutOfRangeException in MaintainabilityAnalyzers AvoidStaticClassesAnalyzer

### ISSUE THREAD

**Issue by jafaber** [philips-software/roslyn-analyzers#777]
The below two exceptions happen when building through Resharper in a TeamCity CI setup. Looks like thread-safety issues.

```
Analyzer 'Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.AvoidStaticClassesAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.'.
Exception occurred with following context:

System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at Philips.CodeAnalysis.Common.AllowedSymbols.RegisterLine(String line)
   at Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.AvoidStaticClassesAnalyzer.InitializeCompilation(CompilationStartAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1182
-----

Suppress the following diagnostics to disable this analyzer: PH2045
```
--------------------

```
Analyzer 'Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.AvoidStaticClassesAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at Philips.CodeAnalysis.Common.AllowedSymbols.RegisterLine(String line)
   at Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability.AvoidStaticClassesAnalyzer.InitializeCompilation(CompilationStartAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1182
-----

Suppress the following diagnostics to disable this analyzer: PH2045
```

**Comment by ynsehoornenborg** [comment]
Wow ! This indicated that TeamCity calls `CompilationStartAction` more than once on the same `DiagnosticAnalyzer` instance, fro different threads. I would consider this a bug at TeamCity end.

However, we should be able to make ourselves robust against this scenario.
